### ISSUE TITLE
markdown parsing problem

### ISSUE THREAD

**Issue by uniphil** [uniphil/commit--blog#32]
test:

Initially, this extension grabbed the content of a CSS file with an XMLHttpRequest and injected it into the bottom of the page. This had a few advantages:
1. Text content could be easy processed and manipulated (admittedly, I wasn't using this for anything).
2. Toggling styles was as easy as adding and removing a <style> element from <body>.
3. In theory, this strategy would beat out almost every other style rule (some inline styles excepted). [User `!important` rules used to override author `!important` rules](http://www.w3.org/TR/CSS2/cascade.html#cascading-order), but Chrome [no-longer does user stylesheets](https://src.chromium.org/viewvc/chrome?revision=234007&view=revision). I figured an aggressively `!important` author stylesheet added at the very bottom of the page was pretty solid.

After some testing, I realized that `!important` styles from `content_scripts` injection (along with chrome.tabs.insertCSS) actually _do_ take precedence over author stylesheets. Since 3) was the key consideration for my original decision, I re-wrote the extension to inject a stylesheet from `content_scripts`.

This change in architecture had pros and cons.

```
+ Improved chance of dark theme winning out over author styles.
+ Allowed styles to be applied before any other DOM is constructed, substantially reducing time-to-darkness.
+ Simplified the callbacks between background.js and client.js, reduced code, and made the entire extension easier to reason about.

- With 1) above, I could've handled variant rules (eg. specificityHelper) with a few regular expressions. Locking into a static stylesheet added some huge copypastas, tripling the size of main.css.
- Injected stylesheets aren't accessible once they've been added. Rather than "turning the styles off" like in 2), the best option was to add a toggle class to <body>.
- Rewrites take time.
```

This commit was essentially a full rewrite, so I changed some smaller things while I was at it:
- Styles now look for :not(.off) instead of .on. This makes the default dark and avoids a Blinding White Flash before the class changes.
- Added id specificity helpers; it's discussed further in client.js:24.
- Renamed some files for clarity.

I came across some unfortunate Chromium bugs while working on this, which caused me to dive into that project. It's huge! Lots of fun to poke around :)

**Comment by uniphil** [comment]
<span class="abc123">hello</span>
<style>
.abc123 { color: red; }
</style>

**Comment by rileyjshaw** [comment]
🎉

**Comment by rileyjshaw** [comment]
😅 I came here to report this exact problem.

**Comment by rileyjshaw** [comment]
^ oh hey same

🧠🗑

**Comment by uniphil** [comment]
i... i can't remember what the problem was. can you remind me? 😅

**Comment by rileyjshaw** [comment]
Hahah yeah no sweat! I think the “<body>” in https://rileyjshaw.commit--blog.com/rileyjshaw/dark-theme-everywhere/e2592c54bf110e35957a6c093a79999c3a1047bb threw off the rest of the parser.

**Comment by uniphil** [comment]
ahhhh right, gotcha. kind of wild, since commit--blog actually calls out to github's own markdown rendering service to render the messages.

...i've been meaning to replace it especially since hacking around it for #33 , and also because

<img width="770" alt="Screen Shot 2021-03-13 at 19 07 18" src="https://user-images.githubusercontent.com/205128/111053163-6bb0a480-842f-11eb-85ea-4ecee7facce9.png">

commonmark
says
[no
auto
brs](https://spec.commonmark.org/dingus/?text=one%0Atwo)
for
single
newlines

<img width="108" alt="Screen Shot 2021-03-13 at 19 16 26" src="https://user-images.githubusercontent.com/205128/111053346-12497500-8431-11eb-9207-5474809eca13.png">

**Comment by rileyjshaw** [comment]
> commit--blog actually calls out to github's own markdown rendering service

🤯 whaa! that’s so weird!

**Comment by uniphil** [comment]
ok, testing a fix that you can preview by adding `?rr=1` to the url -- https://rileyjshaw.commit--blog.com/rileyjshaw/dark-theme-everywhere/e2592c54bf110e35957a6c093a79999c3a1047bb?rr=1

couple things i've found that still need to be fixed (fenced code blocks with language names got a bit messed), but it feels achievable!

**Comment by rileyjshaw** [comment]
This is a zillion times better!!! My shitty markdown doesn’t deserve this much love 💖

**Comment by uniphil** [comment]
ok hopefully all the regressions are fixed now 🤞🏼 

markdown rendering is now versioned in the database, so old posts won't re-render unless you request it (look for a button called "rerender"). (also the `?rr=1` hack is removed)

Checking the latest rendering on your [`dark-theme-everywhere`](https://rileyjshaw.commit--blog.com/rileyjshaw/dark-theme-everywhere/e2592c54bf110e35957a6c093a79999c3a1047bb) post, and I think it's mostly correct, though it does try to syntax-highlight "strings" in your pros/cons list from apostrophes. 🤔 Not sure what language/why it's inferring that. It should probably not try to auto-infer the language I guess.

**Comment by rileyjshaw** [comment]
# YOOOOOOOOO

# THIS WAS LOGGED IN 2015 AND YOU ACTUALLY CLOSED IT OUT

# THAT’S EPIC AND YOU ARE SO EPIC

# COMMIT--BLOG FOREVER!!!!!!!!!!!!!!!!!!!!!

**Comment by rileyjshaw** [comment]
Thank you so much 💖 I love this project

**Comment by rileyjshaw** [comment]
I just clicked `rerender` and it worked PERFECTLY. Also that workflow is so cool!! I’m super stoked about this.

**Comment by rileyjshaw** [comment]
👯

**Comment by uniphil** [comment]
# ❤️ ❤️ ❤️ ❤️ 💞

**Comment by uniphil** [comment]
I'm so glad the rerender worked 😅 lots of 2015-era code still to update but I'm still excited about this thing too!!!
