### ISSUE TITLE
Pull images from raw.githubusercontent?

### ISSUE THREAD

**Issue by rileyjshaw** [uniphil/commit--blog#33]
_I'm opening this to start a discussion more than anything. The raw.githubusercontent solution seems overly platform-specific, and it probably violates ToS._

With that out of the way:

It would be nice for linked images to appear inline! For instance, [I just published a commit where I copypasta'd the README into my commit body](http://rileyjshaw.commit--blog.com/rileyjshaw/plop/5efe71827c2575cbd09dc30669e9c1a63fc625db). Those three broken image links at the top [link to internal images, as seen here](https://github.com/rileyjshaw/plop/blob/5efe71827c2575cbd09dc30669e9c1a63fc625db/README.md).

Since we have the commit hash, user, and repo name, one option would be to construct the raw.githubusercontent URL and replace relative links with an absolute link. For instance,

```
![Hello world](https://raw.githubusercontent.com/rileyjshaw/plop/5efe71827c2575cbd09dc30669e9c1a63fc625db/img/hello_world.gif)
```
Yields:
![Hello world](https://raw.githubusercontent.com/rileyjshaw/plop/5efe71827c2575cbd09dc30669e9c1a63fc625db/img/hello_world.gif)

I'm happy to work on this! Just wanted to start a discussion and define a direction before digging in.

**Comment by rileyjshaw** [comment]
Just ran into this again. We could also just remove the links and indicate that an image _was_ there. Thoughts?

**Comment by uniphil** [comment]
yo this was a genius suggestion! 1 year + 2 months late but it should work now! ❤️

**Comment by rileyjshaw** [comment]
Yahoo, thanks!
