### ISSUE TITLE
don't try to infer language for code blocks

### ISSUE THREAD

**Issue by uniphil** [uniphil/commit--blog#49]
only do fancy highlighting if a language is explicitly given, because sometimes you just want to use an apostrophe:

<img width="723" alt="Screen Shot 2021-04-04 at 19 46 23" src="https://user-images.githubusercontent.com/205128/113524722-82ee3800-957e-11eb-978f-d45072c3715e.png">

[test case](https://rileyjshaw.commit--blog.com/rileyjshaw/dark-theme-everywhere/e2592c54bf110e35957a6c093a79999c3a1047bb) from #32

**Comment by rileyjshaw** [comment]
👯 amazing
